<h2>.then .catch .finally</h2>

<ul class="list-point">
	<li>.then и .catch подписка на изменение промиса</li>
	<li>в .then и .catch передается функция-коллбэк</li>
	<li>.then и .catch возвращают новый промис, поэтому их можно использовать по цепочке</li>
</ul>

<v-code lang="js" title="">
const promise = Promise.resolve(1);

promise
	// Promise.resolve вернул "1"
	.then(data => console.log(data)) // "1"

	// then ничего не вернул
	.then(data => {
		console.log(data); // "undefined"
		return 2;
	})

	// then вернул "2"
	.then(data => {
		console.log(data); // "2"
		throw new Error('Api Error')
	})

	// предудущий then бросил ошибку
	.then(data => console.log('Hello'))

	// минуя then попадаем в catch
	.catch(error => {
		console.log(error.message); // "Api Error"
		return 3;
	})

	// catch вернул "3"
	.then(data => {
		console.log(data); // "3"
		return 4;
	})

	// then вернул 4, но finally пропустит его мимо себя
	.finally(data => { 
		console.log(data); // "undefined"
		return 5;
	})

	// из finally вернули "5", но результат берется из предудщего then или catch
	.then(data => console.log(data)) // "4"
</v-code>

<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
<h3>Аргументы .then</h3>
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->

<!------------------------------------------------------------->
<h4>1. Один аргумент</h4>
<!------------------------------------------------------------->
<v-code lang="js" title="">
promise
	<u-code>.then</u-code>(result => {
        console.log(result);
    })
</v-code>

<!------------------------------------------------------------->
<h4>2. Два аргумента</h4>
<!------------------------------------------------------------->
<ul class="list-point">
    <li>Первый аргумент - в случае успеха</li>
    <li>Второй аргумент - в случае ошибки</li>
</ul>

<v-two-code type="js;js" comment=".then;.then и .catch">
<template v-slot:first>
promise
	.then((result) => { 
		console.log(result); 
	}, (error) => {
		console.log(error);
	})
</template>
<template v-slot:last>
promise
	.then((result) => { 
		console.log(result); 
	})
	.catch((error) => { 
		console.log(error);
	})
</template>
</v-two-code>

<v-code lang="js" title="">
// передача null первым аргументом
promise
	.then(null, (error) => {
		console.log(error);
	})
</v-code>

<!------------------------------------------------------------->
<h4>3. Вызванная функция в аргументе</h4>
<!------------------------------------------------------------->
<ul class="list-point">
    <li>Вызванная функция в аргументе пропускается</li>
</ul>

<v-code lang="js" title="">
promise<u-code>.then</u-code>(functionResolve())
</v-code>
